x-environment: &environment
  env_file:
    - path: ./.env.example
      required: true
    - path: ./.env
      required: false

services:
  forum:
    <<: *environment
    image: ghcr.io/codersclub/forum:${BUILD_VERSION:-0.0.1}
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: ${APP_ENV:-dev}
      args:
        BUILD_FPM_VERSION: ${BUILD_FPM_VERSION:-7.4-fpm}
    container_name: sources-forum
    restart: on-failure
    ports:
      - "${BUILD_FPM_PUBLIC_PORT:-9000}:9000"
    volumes:
      - composer:/home/sources/.composer:rw
      - ./:/home/sources/forum.sources.ru:rw
    profiles:
      - ''
      - backend
      - build
      - forum
    networks:
      - forum
      - database

  mysql:
    <<: *environment
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
      args:
        BUILD_MYSQL_VERSION: ${BUILD_MYSQL_VERSION:-9.6}
    container_name: sources-mysql
    volumes:
      - mysql_data:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-invision}
      - MYSQL_USER=${DB_USERNAME:-user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "${BUILD_DB_PUBLIC_PORT:-3306}:3306"
    profiles:
      - ''
      - backend
      - infrastructure
    networks:
      - database

  server:
    <<: *environment
    build:
      context: .
      dockerfile: docker/angie/Dockerfile
      args:
        BUILD_SERVER_VERSION: ${BUILD_SERVER_VERSION:-1.10.3-minimal}
    container_name: sources-server
    volumes:
      - ./:/home/sources/forum.sources.ru:ro
    ports:
      - "${BUILD_SERVER_HTTP_PUBLIC_PORT:-80}:80"
      - "${BUILD_SERVER_HTTPS_PUBLIC_PORT:-443}:443"
    profiles:
      - ''
      - backend
      - infrastructure
    networks:
      - forum

networks:
  forum:
  database:

volumes:
  mysql_data:
  composer:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=${UID:-1000}"
