#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli') {
    exit(1);
}

ini_set('display_errors', 1);
//error_reporting(E_ALL);
set_time_limit(0);

// fix date issues
if (function_exists('date_default_timezone_set')) {
    date_default_timezone_set('UTC');
}

array_shift($argv);
define('SCRIPT_NAME', basename(__FILE__)); //script name
$status = 0;

if ($argc >= 2) {
    require 'app/console_bootstrap.php';
    $commandName = array_shift($argv);
    try{
        fputs(STDOUT, \Console\Manager::getInstance()->execute($commandName, $argv));
        fputs(STDOUT, PHP_EOL);
    }catch(\Exception $e){
        fputs(STDERR, $e->getMessage() . PHP_EOL);
    }
} else {
    fputs(
        STDERR,
        'You must specify a command to execute. Use "' . SCRIPT_NAME . ' list" to get full list of commands' . PHP_EOL
    );
    $status = 1;
}
exit($status);
