<!--GLOBAL.MESSAGE-->
<table id="QuickLinks" class="b-news-wrapper">
    <tr id="SecondNewsRow" class="b-news-row">
        <td class="news-wrapper news-second-wrapper"><!--IBF.SECONDNEWSLINK--></td>
        <td align="right" class="b-quick-login-wrapper"><!--IBF.QUICK_LOG_IN--></td>
    </tr>
    <tr id="FirstNewsRow" class="b-news-row">
        <td class="news-wrapper news-first-wrapper"><!--IBF.NEWSLINK--></td>
        <td><!-- --></td>
    </tr>
    <tr id="PollsRow" class="b-polls-row b-news-row">
        <td class="polls-wrapper"><!--IBF.OUR_POLL_LINK--></td>
        <td id="ShowAllWrapper" class="show-all-wrapper"><?= $show_all ?></td>
    </tr>
</table>
