<?php

class Migration_2014_09_02_07_17_55 extends MpmMigration
{

    public function up(PDO &$pdo)
    {
        $pdo->exec('DROP TABLE IF EXISTS ibf_templates');
        $pdo->exec('DROP TABLE IF EXISTS ibf_skin_templates');
        $pdo->exec('DROP TABLE IF EXISTS ibf_tmpl_names');
        $pdo->exec('DROP TABLE IF EXISTS ibf_skins');
        $pdo->exec('DROP TABLE IF EXISTS ibf_macro');
        $pdo->exec('DROP TABLE IF EXISTS ibf_macro_name');
    }

    public function down(PDO &$pdo)
    {
        $pdo->exec(
            'CREATE TABLE IF NOT EXISTS ibf_templates (
              tmid int(10) NOT NULL AUTO_INCREMENT,
              template longtext,
              `name` varchar(128) DEFAULT NULL,
              PRIMARY KEY (tmid)
            ) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8'
        );
        if (file_exists(__DIR__ . '/../../htdocs/Skin/s1/wrapper.tpl.php')) {
            ob_start();
            require __DIR__ . '/../../htdocs/Skin/s1/wrapper.tpl.php';
            $template = ob_get_clean();
        } else {
            $template = '';
        }
        $pdo->prepare('INSERT INTO ibf_templates (template, name) VALUES (:template, :name)')
            ->execute(
                [
                    ':template' => $template,
                    ':name'     => 'Invision Board Standard'
                ]
            );
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS ibf_tmpl_names (
                  skid int(10) NOT NULL AUTO_INCREMENT,
                  skname varchar(60) NOT NULL DEFAULT 'Invision Board',
                  author varchar(250) DEFAULT '',
                  email varchar(250) DEFAULT '',
                  url varchar(250) DEFAULT '',
                  PRIMARY KEY (skid)
            ) ENGINE=MyISAM DEFAULT CHARSET=utf8"
        );
        $pdo->exec(
            "INSERT INTO ibf_tmpl_names (skname, author, email, url) VALUES
          ('Invision Power Board Template Set','Invision Power Board','skins@invisionboard.com','http://www.invisionboard.com')
          "
        );

        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS ibf_skins (
              uid int(10) NOT NULL AUTO_INCREMENT,
              sname varchar(100) NOT NULL DEFAULT '',
              sid int(10) NOT NULL DEFAULT '0',
              set_id int(5) NOT NULL DEFAULT '0',
              tmpl_id int(10) NOT NULL DEFAULT '0',
              macro_id int(10) NOT NULL DEFAULT '1',
              css_id int(10) NOT NULL DEFAULT '1',
              img_dir varchar(200) DEFAULT '1',
              tbl_width varchar(250) DEFAULT NULL,
              tbl_border varchar(250) DEFAULT NULL,
              hidden tinyint(1) NOT NULL DEFAULT '0',
              default_set tinyint(1) NOT NULL DEFAULT '0',
              white_background varchar(30) DEFAULT NULL,
              PRIMARY KEY (uid),
              KEY tmpl_id (tmpl_id),
              KEY css_id (css_id),
              KEY sid (sid)
            ) ENGINE=MyISAM AUTO_INCREMENT=16 DEFAULT CHARSET=utf8;"
        );
        try {
            $pdo->exec(
                "INSERT INTO ibf_skins VALUES
                (1,'Main',0,1,1,12,1,'1','95%','#999999',0,1,'bgColor=#ffffff'),
                (4,'FAQ',2,4,1,12,1,'1',NULL,NULL,1,0,'bgColor=#ffffff'),
                (6,'New Year - graphics',4,1,1,13,5,'NBS-Snow-262',NULL,NULL,0,0,'bgColor=#ffffff'),
                (7,'New Year - text',5,1,1,12,5,'NBS-Snow-262',NULL,NULL,0,0,'bgColor=#ffffff'),
                (8,'Sources Winter Graphic',6,1,1,11,6,'Invision-058',NULL,NULL,0,0,'bgColor=#ffffff'),
                (9,'Sources Winter Text',7,1,1,12,6,'Invision-058',NULL,NULL,0,0,'bgColor=#ffffff'),
                (11,'Xpression Final',8,1,1,12,8,'Xpressio-296',NULL,NULL,0,0,'bgColor=#f4f4f4'),
                (13,'Text Skin',9,1,1,16,10,'Text_Ski-187',NULL,NULL,0,0,'bgColor=#ffffff'),
                (14,'Mastilior',10,1,1,17,11,'Sources_-383',NULL,NULL,0,0,'id=&#39;ibwrapper&#39;'),
                (15,'Black Label',11,1,1,12,14,'BlackLabel',NULL,NULL,0,0,'bgColor=#202020');"
            );
        } catch (Exception $e) {
        }
        try {
            $pdo->exec(
                "CREATE TABLE IF NOT EXISTS ibf_macro (macro_id smallint(3) NOT NULL AUTO_INCREMENT, macro_value varchar(200) DEFAULT NULL, macro_replace text, can_remove tinyint(1) DEFAULT '0', macro_set smallint(3) NOT NULL DEFAULT '0', PRIMARY KEY (macro_id), KEY macro_set (macro_set)) ENGINE=MyISAM AUTO_INCREMENT=1664 DEFAULT CHARSET=utf8;"
            );
            $pdo->exec(
                "CREATE TABLE ibf_macro_name (set_id smallint(3) NOT NULL DEFAULT '0', set_name varchar(200) DEFAULT NULL, PRIMARY KEY (set_id)) ENGINE=MyISAM DEFAULT CHARSET=utf8;"
            );
            $pdo->exec(
                "INSERT INTO ibf_macro_name VALUES (11,'Invision Power Board Winter'), (12,'IPB Default Macro Set'), (13,'NBS-SnowF'), (16,'Text Skin Macros'), (17,'Sources RU Club Mastystyle');"
            );
            $pdo->exec(
                "INSERT INTO ibf_macro
(macro_id, macro_value, macro_replace, can_remove, macro_set)
VALUES
(1469,'atb_calendar','<img src=\'<#IMG_DIR#>/atb_calendar.gif\' border=\"0\" alt=\"\">',1,17),
(1473,'F_MINUS','<img src=\'<#IMG_DIR#>/minus.gif\' border=\'0\' alt=\'-\'>',1,17),
(1474,'F_PLUS','<img src=\'<#IMG_DIR#>/plus.gif\' border=\'0\' alt=\'+\'>',1,17),
(1475,'C_LOCKED_CAT','<img src=\'<#IMG_DIR#>/bf_readonly.gif\' border=\'0\'  alt=\'Премодерация\'>',1,17),
(1476,'WARN_1','<img src=\'<#IMG_DIR#>/warn1.gif\' border=\'0\'  alt=\'X----\'>',1,17),
(1477,'WARN_0','<img src=\'<#IMG_DIR#>/warn0.gif\' border=\'0\'  alt=\'-----\'>',1,17),
(1478,'WARN_2','<img src=\'<#IMG_DIR#>/warn2.gif\' border=\'0\'  alt=\'XX---\'>',1,17),
(1479,'F_RULES','<img src=\'<#IMG_DIR#>/forum_rules.gif\' border=\'0\'  alt=\'!\'>',1,17),
(1480,'CAL_NEWEVENT','<img src=\'<#IMG_DIR#>/cal_newevent.gif\' border=\'0\'  alt=\'Добавить новое\'>',1,17),
(1481,'T_QREPLY','<b>Быстрый ответ</b>',1,17),
(1482,'T_OPTS','<img src=\'<#IMG_DIR#>/t_options.gif\' border=\'0\'  alt=\'Опции темы\'>',1,17),
(1483,'ADDRESS_CARD','<img src=\'<#IMG_DIR#>/addresscard.gif\' border=\'0\'  alt=\'Профиль\'>',1,17),
(1484,'INTEGRITY_MSGR','<img src=\'<#IMG_DIR#>/p_im.gif\' border=\'0\'  alt=\'IM\'>',1,17),
(1485,'BR_REDIRECT','<img src=\'<#IMG_DIR#>/br_redirect.gif\' border=\'0\'  alt=\'Ссылка\'>',1,17),
(1486,'LAST_POST','<img src=\'<#IMG_DIR#>/lastpost.gif\' border=\'0\'  alt=\'Последнее\'>',1,17),
(1487,'NEW_POST','<img src=\'<#IMG_DIR#>/new.gif\' border=\'0\'  alt=\'Новое\' title=\'Новое\' hspace=2>',1,17),
(1488,'CAT_IMG','<img src=\'<#IMG_DIR#>/nav_m.gif\' border=\'0\'  alt=\'&gt;\' width=\'8\' height=\'8\'>',1,17),
(1489,'P_REPORT','Позвать модератора',1,17),
(1490,'P_MSN','<img src=\'<#IMG_DIR#>/p_msn.gif\' border=\'0\' alt=\'MSN\'>',1,17),
(1491,'P_YIM','<img src=\'<#IMG_DIR#>/p_yim.gif\' border=\'0\' alt=\'Yahoo\'>',1,17),
(1492,'P_QUOTE','Цитата',1,17),
(1493,'P_WEBSITE','<img src=\'<#IMG_DIR#>/p_www.gif\' border=\'0\'  alt=\'Сайт\'>',1,17),
(1494,'P_MSG','<img src=\'<#IMG_DIR#>/p_pm.gif\' border=\'0\'  alt=\'Перс. сообщ.\'>',1,17),
(1495,'P_ICQ','<img src=\'<#IMG_DIR#>/p_icq.gif\' border=\'0\'  alt=\'ICQ\'>',1,17),
(1496,'P_EMAIL','<img src=\'<#IMG_DIR#>/p_email.gif\' border=\'0\'  alt=\'Мыло\'>',1,17),
(1497,'P_DELETE','Удалить',1,17),
(1498,'P_EDIT','Изменить',1,17),
(1499,'P_AOL','<img src=\'<#IMG_DIR#>/p_aim.gif\' border=\'0\'  alt=\'AOL\'>',1,17),
(1500,'M_UNREAD','<img src=\'<#IMG_DIR#>/f_norm.gif\' border=\'0\'  alt=\'Есть новые\'>',1,17),
(1501,'M_READ','<img src=\'<#IMG_DIR#>/f_norm_no.gif\' border=\'0\'  alt=\'Нет новых.\'>',1,17),
(1502,'CAMERA','<img src=\'<#IMG_DIR#>/camera.gif\' border=\'0\'  alt=\'Фото\'>',1,17),
(1503,'NO_PHOTO','<img src=\'<#IMG_DIR#>/nophoto.gif\' border=\'0\'  alt=\'Нет фотографии\'>',1,17),
(1504,'F_STATS','<a href=\'http://forum.sources.ru/index.php?act=Help&CODE=01&HID=21\'><img src=\'<#IMG_DIR#>/stats.gif\' border=\'0\'  alt=\'Статистика\'><a/>',1,17),
(1505,'F_NAV','<img src=\'<#IMG_DIR#>/nav.gif\' border=\'0\'  alt=\'&gt;\'>',1,17),
(1506,'F_NAV_SEP','<img src=\'<#IMG_DIR#>/open.gif\' border=\'0\'  alt=\'\'>&nbsp;&nbsp;',1,17),
(1507,'F_ACTIVE','<img src=\'<#IMG_DIR#>/user.gif\' border=\'0\'  alt=\'Участники\'>',1,17),
(1508,'C_ON_RES','<img src=\'<#IMG_DIR#>/br_new.gif\' border=\'0\'  alt=\'Есть новые\' >',1,17),
(1509,'C_ON_CAT','<img src=\'<#IMG_DIR#>/bc_new.gif\' border=\'0\'  alt=\'Есть новые\'>',1,17),
(1510,'C_ON','<img src=\'<#IMG_DIR#>/bf_new.gif\' border=\'0\'  alt=\'Есть новые\'>',1,17),
(1511,'C_OFF_RES','<img src=\'<#IMG_DIR#>/br_nonew.gif\' border=\'0\'  alt=\'Нет новых\'>',1,17),
(1512,'C_OFF_CAT','<img src=\'<#IMG_DIR#>/bc_nonew.gif\' border=\'0\'  alt=\'Нет новых\'>',1,17),
(1513,'C_OFF','<img src=\'<#IMG_DIR#>/bf_nonew.gif\' border=\'0\'  alt=\'Нет новых\'>',1,17),
(1514,'C_LOCKED','<img src=\'<#IMG_DIR#>/bf_readonly.gif\' border=\'0\'  alt=\'Премодерация\'>',1,17),
(1515,'B_POLL_NN_DOT','<img src=\'<#IMG_DIR#>/f_poll_no_dot.gif\' border=\'0\' alt=\'Нет новых голосов.\'>',1,17),
(1516,'B_POLL_DOT','<img src=\'<#IMG_DIR#>/f_poll_dot.gif\' border=\'0\' alt=\'Есть новые голоса.\'>',1,17),
(1517,'B_NORM_DOT','<img src=\'<#IMG_DIR#>/f_norm_no_dot.gif\' border=\'0\' alt=\'Нет новых\'>',1,17),
(1518,'B_HOT_NN_DOT','<img src=\'<#IMG_DIR#>/f_hot_no_dot.gif\' border=\'0\' alt=\'Нет новых\'>',1,17),
(1519,'B_NEW_DOT','<img src=\'<#IMG_DIR#>/f_norm_dot.gif\' border=\'0\' alt=\'Есть новые\'>',1,17),
(1520,'B_HOT_DOT','<img src=\'<#IMG_DIR#>/f_hot_dot.gif\' border=\'0\' alt=\'Есть новые\'>',1,17),
(1521,'B_POLL_NN','<img src=\'<#IMG_DIR#>/f_poll_no.gif\' border=\'0\'  alt=\'Нет новых голосов.\'>',1,17),
(1522,'B_POLL','<img src=\'<#IMG_DIR#>/f_poll.gif\' border=\'0\'  alt=\'Есть новые голоса.\'>',1,17),
(1523,'B_PIN','<img src=\'<#IMG_DIR#>/f_pinned.gif\' border=\'0\'  alt=\'Важный\'>',1,17),
(1524,'B_NORM','<img src=\'<#IMG_DIR#>/f_norm_no.gif\' border=\'0\'  alt=\'Нет новых.\'>',1,17),
(1525,'B_NEW','<img src=\'<#IMG_DIR#>/f_norm.gif\' border=\'0\'  alt=\'Есть новые\'>',1,17),
(1526,'B_MOVED','<img src=\'<#IMG_DIR#>/f_moved.gif\' border=\'0\'  alt=\'Перемещена.\'>',1,17),
(1527,'B_LOCKED','<img src=\'<#IMG_DIR#>/f_closed.gif\' border=\'0\'  alt=\'Закрыта.\'>',1,17),
(1528,'B_HOT_NN','<img src=\'<#IMG_DIR#>/f_hot_no.gif\' border=\'0\'  alt=\'Нет новых.\'>',1,17),
(1529,'B_HOT','<img src=\'<#IMG_DIR#>/f_hot.gif\' border=\'0\'  alt=\'Горячая тема.\'>',1,17),
(1530,'A_POLL','<b>Новое голосование</b>',1,17),
(1531,'A_STAR','<img src=\'<#IMG_DIR#>/pip.gif\' border=\'0\'  alt=\'*\'>',1,17),
(1532,'A_POST','<b>Новая тема</b>',1,17),
(1533,'A_REPLY','<b>Ответить</b>',1,17),
(1534,'A_POLLONLY_B','<font color=gray><b>закрыто</b></font>',1,17),
(1535,'A_MOVED_B','<font color=gray><b>перемещена</b></font>',1,17),
(1536,'A_LOCKED_B','<font color=gray><b>закрыта</b></font>',1,17),
(1537,'WARN_3','<img src=\'<#IMG_DIR#>/warn3.gif\' border=\'0\'  alt=\'XXX--\'>',1,17),
(1538,'WARN_4','<img src=\'<#IMG_DIR#>/warn4.gif\' border=\'0\'  alt=\'XXXX-\'>',1,17),
(1539,'WARN_5','<img src=\'<#IMG_DIR#>/warn5.gif\' border=\'0\'  alt=\'XXXXX\'>',1,17),
(1540,'WARN_ADD','<img src=\'<#IMG_DIR#>/warn_add.gif\' border=\'0\'  alt=\'+\'>',1,17),
(1541,'WARN_MINUS','<img src=\'<#IMG_DIR#>/warn_minus.gif\' border=\'0\'  alt=\'-\'>',1,17),
(1542,'C_MINUS','<img src=\'<#IMG_DIR#>/minimize.gif\' border=\'0\' alt=\' - \'>',1,17),
(1543,'C_PLUS','<img src=\'<#IMG_DIR#>/maximize.gif\' border=\'0\' alt=\' + \'>',1,17),
(1544,'REP_ADD','<img src=\'<#IMG_DIR#>/rep_plus.gif\' border=\'0\' alt=\'+\'>',1,17),
(1545,'REP_MINUS','<img src=\'<#IMG_DIR#>/rep_minus.gif\' border=\'0\'  alt=\'-\'>',1,17),
(1546,'REP_UP','<img src=\'<#IMG_DIR#>/rep_up.gif\' border=\'0\'  alt=\'+\'>',1,17),
(1547,'REP_DOWN','<img src=\'<#IMG_DIR#>/rep_down.gif\' border=\'0\'  alt=\'-\'>',1,17),
(1548,'atb_magazine','·&nbsp;&nbsp;',1,16),
(1549,'atb_magazine','<img src=\'<#IMG_DIR#>/atb_members.gif\' border=\"0\" alt=\'Журнал\'>',1,17),
(1550,'atb_magazine','<img src=\'<#IMG_DIR#>/atb_members.gif\' border=\"0\">',1,11),
(1551,'atb_magazine','<img src=\'<#IMG_DIR#>/atb_members.gif\' border=\"0\" alt=\'Журнал\'>',1,12),
(1552,'atb_magazine','<img src=\'<#IMG_DIR#>/atb_members.gif\' border=\"0\" alt=\'Журнал\'>',1,13),
(1553,'P_QUICKQUOTE','<img src=\'<#IMG_DIR#>/p_quickquote.gif\' border=\'0\'  alt=\'Quick Quote\'>',1,11),
(1554,'P_QREPLY','Быстрый ответ',1,12),
(1555,'P_QUICKQUOTE','Быстрая цитата',1,12),
(1556,'P_QUICKQUOTE','<img src=\'<#IMG_DIR#>/p_quickquote.gif\' border=\'0\'  alt=\'Quick Quote\'  style=\'vertical-align: middle;\'/>',1,13),
(1557,'P_QUICKQUOTE','Быстрая цитата',1,16),
(1558,'ONLINE',' (<span class=\'voteprefix\'>Online</span>)',1,11),
(1559,'ONLINE',' (<span class=\'voteprefix\'>Online</span>)',1,12),
(1560,'ONLINE',' (<span class=\'voteprefix\'>Online</span>)',1,13),
(1561,'ONLINE',' (<span class=\'voteprefix\'>Online</span>)',1,16),
(1562,'P_QUICKQUOTE','Быстрая цитата',1,17),
(1563,'ONLINE',' (<span class=\'voteprefix\'>Online</span>)',1,17),
(1564,'P_RESTORE','Восстановить',1,11),
(1565,'P_DECLINE','<img src=\'<#IMG_DIR#>/t_cancel.gif\' border=\'0\' alt=\'\'>',1,11),
(1566,'P_DECLINE','Отклонить',1,12),
(1567,'P_RESTORE','Восстановить',1,12),
(1568,'P_DECLINE','Отклонить',1,13),
(1569,'P_RESTORE','Восстановить',1,13),
(1570,'P_DECLINE','Отклонить',1,17),
(1571,'P_RESTORE','Восстановить',1,17),
(1572,'P_DECLINE','Отклонить',1,16),
(1573,'P_RESTORE','Восстановить',1,16),
(1330,'INTEGRITY_MSGR','IM',1,16),
(1331,'T_QREPLY','Быстрый ответ',1,16),
(1332,'T_OPTS','<b>Опции темы</b>',1,16),
(1333,'ADDRESS_CARD','Карточка пользователя · ',1,16),
(1334,'CAL_NEWEVENT','&nbsp;',1,16),
(1335,'F_RULES','<font color=red><b>Важно:</b></font>',1,16),
(1336,'WARN_0','<img src=\'<#IMG_DIR#>/warn0.gif\' border=\'0\'  alt=\'-----\' />',1,16),
(1337,'WARN_1','<img src=\'<#IMG_DIR#>/warn1.gif\' border=\'0\'  alt=\'X----\' />',1,16),
(1338,'WARN_2','<img src=\'<#IMG_DIR#>/warn2.gif\' border=\'0\'  alt=\'XX---\' />',1,16),
(1339,'WARN_3','<img src=\'<#IMG_DIR#>/warn3.gif\' border=\'0\'  alt=\'XXX--\' />',1,16),
(1340,'WARN_4','<img src=\'<#IMG_DIR#>/warn4.gif\' border=\'0\'  alt=\'XXXX-\' />',1,16),
(1341,'WARN_5','<img src=\'<#IMG_DIR#>/warn5.gif\' border=\'0\'  alt=\'XXXXX\' />',1,16),
(1342,'WARN_ADD','<font color=red>+</font>',1,16),
(1343,'WARN_MINUS','<font color=green>—</font>',1,16),
(1344,'REP_ADD','<font color=green>+</font>',1,16),
(1345,'REP_MINUS','<font color=red>—</font>',1,16),
(1471,'atb_search','<img src=\'<#IMG_DIR#>/atb_search.gif\' border=\"0\" alt=\"\">',1,17),
(1346,'REP_UP','<font color=\"#006699\" size=\"+2\"><b>+</b></font>',1,16),
(1347,'REP_DOWN','<font color=\"red\" size=\"+2\"><b>-</b></font>',1,16),
(1278,'A_LOCKED_B','<font color=\'red\'>Закрыто</font>',1,16),
(1279,'A_MOVED_B','<font color=\'red\'>Перемещено</font>',1,16),
(1280,'A_POLLONLY_B','<font color=\'red\'>Добавление сообщений запрещено</font>',1,16),
(1281,'A_POST','Новая тема',1,16),
(1282,'A_REPLY','Ответить',1,16),
(1283,'A_POLL','Новый опрос',1,16),
(1284,'A_STAR','*',1,16),
(1285,'B_HOT','<font title=\'Горячая тема (есть новые ответы)\' size=\'+1\' color=\'FF6600\'><b>#</b></font>',1,16),
(1286,'B_HOT_NN','<font title=\'Горячая тема (нет новых ответов)\' size=\'+1\' color=\'FFCC99\'><b>#</b></font>',1,16),
(1287,'B_LOCKED','<font title=\'Закрытая тема\' size=\'+1\' color=\'88A0C0\'><b>x</b></font>',1,16),
(1288,'B_MOVED','<font title=\'Перемещенная тема\' size=\'+1\' color=\'88A0C0\'><b>></b></font>',1,16),
(1289,'B_NEW','<font title=\'Открытая тема (есть новые ответы)\' size=\'+1\' color=\'0000FF\'><b>#</b></font>',1,16),
(1290,'B_NORM','<font title=\'Открытая тема (нет новых ответов)\' size=\'+1\' color=\'CCCCFF\'><b>#</b></font>',1,16),
(1291,'B_PIN','<font title=\'Важная тема\' size=\'+1\' color=\'88A0C0\'><b>!</b></font>',1,16),
(1292,'B_POLL','<font title=\'Опрос (есть новые ответы)\' size=\'+1\' color=\'00FF00\'><b>#</b></font>',1,16),
(1293,'B_POLL_NN','<font title=\'Опрос (нет новых ответов)\' size=\'+1\' color=\'99CC66\'><b>#</b></font>',1,16),
(1294,'B_HOT_DOT','<font title=\'Горячая тема (есть новые ответы)\' size=\'+1\' color=\'FF6600\'><b>#&#183;</b></font>',1,16),
(1295,'B_NEW_DOT','<font title=\'Открытая тема (есть новые ответы)\' size=\'+1\' color=\'0000FF\'><b>#&#183;</b></font>',1,16),
(1296,'B_HOT_NN_DOT','<font title=\'Горячая тема (нет новых ответов)\' size=\'+1\' color=\'FFCC99\'><b>#&#183;</b></font>',1,16),
(1297,'B_NORM_DOT','<font title=\'Открытая тема (нет новых ответов)\' size=\'+1\' color=\'CCCCFF\'><b>#&#183;</b></font>',1,16),
(1298,'B_POLL_DOT','<font title=\'Опрос (есть новые ответы)\' size=\'+1\' color=\'00FF00\'><b>#&#183;</b></font>',1,16),
(1299,'B_POLL_NN_DOT','<font title=\'Опрос (нет новых ответов)\' size=\'+1\' color=\'99CC66\'><b>#&#183;</b></font>',1,16),
(1300,'C_LOCKED','<font title=\"Премодерация\"color=\"red\" size=\"+1\"><b>X</b></font>',1,16),
(1301,'C_OFF','<font title=\"Нет новых сообщений\"color=\"#C4DCF7\" size=\"+1\"><b>X</b></font>',1,16),
(1302,'C_OFF_CAT','<font title=\"Нет новых сообщений\"color=\"#C4DCF7\" size=\"+1\"><b>></b></font>',1,16),
(1303,'C_OFF_RES','<font title=\"Форум под паролем. Нет новых сообщений\"color=\"#C4DCF7\" size=\"+1\"><b>L</b></font>',1,16),
(1304,'C_ON','<font color=\"#006699\" size=\"+2\"><b>+</b></font>',1,16),
(1305,'C_ON_CAT','<font title=\"Есть новые сообщения\"color=\"#006699\" size=\"+2\"><b>></b></font>',1,16),
(1306,'C_ON_RES','<font title=\"Форум под паролем. Есть новые сообщения\"color=\"#006699\" size=\"+2\"><b>L</b></font>',1,16),
(1307,'F_ACTIVE','<font color=\'006699\' face=\'Verdana\' size=\'+1\'><b>:)</b></font>',1,16),
(1308,'F_NAV_SEP','\\ ',1,16),
(1309,'F_NAV','C:\\>',1,16),
(1310,'F_STATS','<a href=\'http://forum.sources.ru/index.php?act=Help&CODE=01&HID=21\' style=\'text-decoration:none\'><font title=\'Статистика форума\' color=\'006699\' face=\'Courier, Verdana\' size=\'+3\'><b>i</b></font></a>',1,16),
(1311,'NO_PHOTO','<font title=\"Нет фото\" size=\"+4\"><b>?</b></font>',1,16),
(1312,'CAMERA','<font title=\'Есть фото\'>Фото</font>',1,16),
(1313,'M_READ','<font title=\'Прочитанное сообщение\' size=\'+1\' color=\'CCCCFF\'><b>#</b></font>',1,16),
(1314,'M_UNREAD','<font title=\'Непрочитанное сообщение\' size=\'+1\' color=\'0000FF\'><b>#</b></font>',1,16),
(1315,'P_AOL','AOL',1,16),
(1316,'P_DELETE','Удалить',1,16),
(1317,'P_EDIT','Изменить',1,16),
(1318,'P_EMAIL','<nobr>E-mail</nobr> · ',1,16),
(1319,'P_ICQ','ICQ',1,16),
(1320,'P_MSG','PM · ',1,16),
(1321,'P_QUOTE','Цитата',1,16),
(1322,'P_WEBSITE','WWW',1,16),
(1323,'P_YIM','YIM',1,16),
(1324,'P_REPORT','Сообщить редакции',1,16),
(1325,'P_MSN','MSN',1,16),
(1326,'CAT_IMG','>',1,16),
(1462,'C_LOCKED_CAT','<img src=\'<#IMG_DIR#>/bf_readonly.gif\' border=\'0\'  alt=\'Премодерация\'>',1,11),
(1327,'NEW_POST','<font face=Arial color=blue><b>New</b></font>',1,16),
(1472,'atb_help','<img src=\'<#IMG_DIR#>/atb_help.gif\' border=\"0\" alt=\"\">',1,17),
(1328,'LAST_POST','<font style=\'text-decoration:none\' title=\'К последнему сообщению темы\'><big>&raquo;</big></font>',1,16),
(1329,'BR_REDIRECT','<font color=\'006699\' size=\"+2\"><b>&raquo;</b></font>',1,16),
(1470,'atb_members','<img src=\'<#IMG_DIR#>/atb_members.gif\' border=\"0\" alt=\"\">',1,17),
(1460,'atb_store','<img src=\'<#IMG_DIR#>/atb_coin.gif\' border=\"0\" alt=\"\">',1,12),
(1461,'atb_store','<img src=\'<#IMG_DIR#>/atb_coin.gif\' border=\"0\" alt=\"\">',1,11),
(1468,'atb_favs','<img src=\'<#IMG_DIR#>/atb_favs.gif\' border=\"0\" alt=\"\">',1,17),
(1459,'atb_store','<img src=\'<#IMG_DIR#>/atb_coin.gif\' border=\"0\" alt=\"\">',1,13),
(1458,'atb_store','·&nbsp;&nbsp;',1,16),
(1457,'atb_favs_new','<img src=\'<#IMG_DIR#>/atb_favs_new.gif\' border=\"0\" alt=\'Избранное. Есть новые.\'>',1,11),
(1454,'atb_favs_new','·  <img src=\'<#IMG_DIR#>/atb_favs_new.gif\' border=\"0\" alt=\'Избранное. Есть новые.\'>',1,16),
(1455,'atb_favs_new','<img src=\'<#IMG_DIR#>/atb_favs_new.gif\' border=\"0\" alt=\'Избранное. Есть новые.\'>',1,13),
(1456,'atb_favs_new','<img src=\'<#IMG_DIR#>/atb_favs_new.gif\' border=\"0\" alt=\'Избранное. Есть новые.\'>',1,12),
(1451,'atb_favs','<img src=\'<#IMG_DIR#>/atb_favs.gif\' border=\"0\" alt=\"\">',1,13),
(1452,'atb_favs','<img src=\'<#IMG_DIR#>/atb_favs.gif\' border=\"0\" alt=\"\">',1,12),
(1453,'atb_favs','<img src=\'<#IMG_DIR#>/atb_favs.gif\' border=\"0\" alt=\"\">',1,11),
(1449,'atb_calendar','<img src=\'<#IMG_DIR#>/atb_calendar.gif\' border=\"0\" alt=\"\">',1,11),
(1450,'atb_favs','·&nbsp;&nbsp;',1,16),
(1465,'C_LOCKED_CAT','<font title=\"Премодерация\"color=\"red\" size=\"+1\"><b>X</b></font>',1,16),
(1447,'atb_calendar','<img src=\'<#IMG_DIR#>/atb_calendar.gif\' border=\"0\" alt=\"\">',1,13),
(1448,'atb_calendar','<img src=\'<#IMG_DIR#>/atb_calendar.gif\' border=\"0\" alt=\"\">',1,12),
(1466,'atb_store','<img src=\'<#IMG_DIR#>/atb_coin.gif\' border=\"0\" alt=\"\">',1,17),
(1446,'atb_calendar','·&nbsp;&nbsp;',1,16),
(1445,'atb_members','·&nbsp;&nbsp;',1,16),
(1444,'atb_members','<img src=\'<#IMG_DIR#>/atb_members.gif\' border=\"0\" alt=\"\">',1,13),
(1443,'atb_members','<img src=\'<#IMG_DIR#>/atb_members.gif\' border=\"0\" alt=\"\">',1,12),
(1442,'atb_members','<img src=\'<#IMG_DIR#>/atb_members.gif\' border=\"0\" alt=\"\">',1,11),
(1439,'atb_search','<img src=\'<#IMG_DIR#>/atb_search.gif\' border=\"0\" alt=\"\">',1,12),
(1441,'atb_search','·&nbsp;&nbsp;',1,16),
(1440,'atb_search','<img src=\'<#IMG_DIR#>/atb_search.gif\' border=\"0\" alt=\"\">',1,13),
(1436,'atb_help','<img src=\'<#IMG_DIR#>/atb_help.gif\' border=\"0\" alt=\"\">',1,12),
(1438,'atb_search','<img src=\'<#IMG_DIR#>/atb_search.gif\' border=\"0\" alt=\"\">',1,11),
(1437,'atb_help','<img src=\'<#IMG_DIR#>/atb_help.gif\' border=\"0\" alt=\"\">',1,13),
(1435,'atb_help','<img src=\'<#IMG_DIR#>/atb_help.gif\' border=\"0\" alt=\"\">',1,11),
(1467,'atb_favs_new','<img src=\'<#IMG_DIR#>/atb_favs_new.gif\' border=\"0\" alt=\'Избранное. Есть новые.\'>',1,17),
(1434,'atb_help','·&nbsp;&nbsp;',1,16),
(1433,'F_PLUS','<img src=\'<#IMG_DIR#>/plus.gif\' border=\'0\' alt=\'+\'>',1,13),
(1432,'F_MINUS','<img src=\'<#IMG_DIR#>/minus.gif\' border=\'0\' alt=\'-\'>',1,13),
(1429,'F_PLUS','<img src=\'<#IMG_DIR#>/plus.gif\' border=\'0\' alt=\'+\'>',1,11),
(1428,'F_MINUS','<img src=\'<#IMG_DIR#>/minus.gif\' border=\'0\' alt=\'-\'>',1,11),
(1424,'F_MINUS','<img src=\'<#IMG_DIR#>/minus.gif\' border=\'0\' alt=\'-\'>',1,12),
(1425,'F_PLUS','<img src=\'<#IMG_DIR#>/plus.gif\' border=\'0\' alt=\'+\'>',1,12),
(1418,'C_PLUS','>>',1,16),
(1464,'C_LOCKED_CAT','<img src=\'<#IMG_DIR#>/bf_readonly.gif\' border=\'0\'  alt=\'Премодерация\'>',1,13),
(1419,'C_MINUS','<<',1,16),
(1421,'F_MINUS','—',1,16),
(1463,'C_LOCKED_CAT','<img src=\'<#IMG_DIR#>/bf_readonly.gif\' border=\'0\'  alt=\'Премодерация\'>',1,12),
(1420,'F_PLUS','+',1,16),
(831,'REP_DOWN','<img src=\'<#IMG_DIR#>/rep_down.gif\' border=\'0\'  alt=\'-\'>',1,11),
(832,'REP_UP','<img src=\'<#IMG_DIR#>/rep_up.gif\' border=\'0\'  alt=\'+\'>',1,11),
(833,'REP_MINUS','<img src=\'<#IMG_DIR#>/rep_minus.gif\' border=\'0\'  alt=\'-\'>',1,11),
(834,'REP_ADD','<img src=\'<#IMG_DIR#>/rep_plus.gif\' border=\'0\'  alt=\'+\'>',1,11),
(1427,'C_MINUS','<img src=\'<#IMG_DIR#>/minimize.gif\' border=\'0\' alt=\' - \'>',1,11),
(836,'B_HOT','<img src=\'<#IMG_DIR#>/f_hot.gif\' border=\'0\'  alt=\'Hot topic\'>',1,11),
(1426,'C_PLUS','<img src=\'<#IMG_DIR#>/maximize.gif\' border=\'0\' alt=\' + \'>',1,11),
(838,'A_STAR','<img src=\'<#IMG_DIR#>/pip.gif\' border=\'0\'  alt=\'*\'>',1,11),
(839,'A_REPLY','<img src=\'<#IMG_DIR#>/t_reply.gif\' border=\'0\'  alt=\'Reply to this topic\'>',1,11),
(840,'A_POLL','<img src=\'<#IMG_DIR#>/t_poll.gif\' border=\'0\'  alt=\'Start Poll\'>',1,11),
(841,'A_POST','<img src=\'<#IMG_DIR#>/t_new.gif\' border=\'0\'  alt=\'Start new topic\'>',1,11),
(842,'A_POLLONLY_B','<img src=\'<#IMG_DIR#>/t_closed.gif\' border=\'0\'  alt=\'Poll Only\'>',1,11),
(843,'A_MOVED_B','<img src=\'<#IMG_DIR#>/t_moved.gif\' border=\'0\'  alt=\'Moved Topic\'>',1,11),
(844,'P_WEBSITE','<img src=\'<#IMG_DIR#>/p_www.gif\' border=\'0\'  alt=\'Users Website\'>',1,11),
(845,'A_LOCKED_B','<img src=\'<#IMG_DIR#>/t_closed.gif\' border=\'0\'  alt=\'Closed Topic\'>',1,11),
(846,'CAL_NEWEVENT','<img src=\'<#IMG_DIR#>/cal_newevent.gif\' border=\'0\'  alt=\'Add New Event\'>',1,11),
(847,'B_POLL_DOT','<img src=\'<#IMG_DIR#>/f_poll_dot.gif\' border=\'0\' alt=\'Есть новые голоса. Добавить в Избранное.\'>',1,11),
(848,'P_QUOTE','<img src=\'<#IMG_DIR#>/p_quote.gif\' border=\'0\'  alt=\'Quote Post\'>',1,11),
(849,'B_MOVED','<img src=\'<#IMG_DIR#>/f_moved.gif\' border=\'0\'  alt=\'Перемещена. Добавить в Избранное.\'>',1,11),
(850,'B_NORM_DOT','<img src=\'<#IMG_DIR#>/f_norm_no_dot.gif\' border=\'0\' alt=\'Нет новых. Добавить в Избранное.\'>',1,11),
(851,'B_HOT_NN_DOT','<img src=\'<#IMG_DIR#>/f_hot_no_dot.gif\' border=\'0\' alt=\'Нет новых. Добавить в Избранное.\'>',1,11),
(852,'WARN_MINUS','<img src=\'<#IMG_DIR#>/warn_minus.gif\' border=\'0\'  alt=\'-\'>',1,11),
(853,'WARN_5','<img src=\'<#IMG_DIR#>/warn5.gif\' border=\'0\'  alt=\'XXXXX\'>',1,11),
(854,'WARN_ADD','<img src=\'<#IMG_DIR#>/warn_add.gif\' border=\'0\'  alt=\'+\'>',1,11),
(855,'WARN_3','<img src=\'<#IMG_DIR#>/warn3.gif\' border=\'0\'  alt=\'XXX--\'>',1,11),
(856,'WARN_4','<img src=\'<#IMG_DIR#>/warn4.gif\' border=\'0\'  alt=\'XXXX-\'>',1,11),
(857,'WARN_2','<img src=\'<#IMG_DIR#>/warn2.gif\' border=\'0\'  alt=\'XX---\'>',1,11),
(858,'WARN_0','<img src=\'<#IMG_DIR#>/warn0.gif\' border=\'0\'  alt=\'-----\'>',1,11),
(859,'WARN_1','<img src=\'<#IMG_DIR#>/warn1.gif\' border=\'0\'  alt=\'X----\'>',1,11),
(860,'T_OPTS','<img src=\'<#IMG_DIR#>/t_options.gif\' border=\'0\'  alt=\'Topic Options\'>',1,11),
(861,'F_RULES','<img src=\'<#IMG_DIR#>/forum_rules.gif\' border=\'0\'  alt=\'Forum Rules\'>',1,11),
(862,'ADDRESS_CARD','<img src=\'<#IMG_DIR#>/addresscard.gif\' border=\'0\'  alt=\'Mini Profile\'>',1,11),
(863,'T_QREPLY','<img src=\'<#IMG_DIR#>/t_qr.gif\' border=\'0\'  alt=\'Fast Reply\'>',1,11),
(864,'BR_REDIRECT','<img src=\'<#IMG_DIR#>/br_redirect.gif\' border=\'0\'  alt=\'Redirect\'>',1,11),
(865,'INTEGRITY_MSGR','<img src=\'<#IMG_DIR#>/p_im.gif\' border=\'0\'  alt=\'Integrity Messenger IM\'>',1,11),
(866,'P_MSN','<img src=\'<#IMG_DIR#>/p_msn.gif\' border=\'0\' alt=\'MSN\'>',1,11),
(867,'LAST_POST','<img src=\'<#IMG_DIR#>/lastpost.gif\' border=\'0\'  alt=\'Last Post\'>',1,11),
(868,'CAT_IMG','<img src=\'<#IMG_DIR#>/nav_m.gif\' border=\'0\'  alt=\'&gt;\' width=\'8\' height=\'8\'>',1,11),
(869,'NEW_POST','<img src=\'<#IMG_DIR#>/newpost.gif\' border=\'0\'  alt=\'Goto last unread\' title=\'Goto last unread\' hspace=2>',1,11),
(870,'P_REPORT','<img src=\'<#IMG_DIR#>/p_report.gif\' border=\'0\'  alt=\'Report Post\'>',1,11),
(871,'P_YIM','<img src=\'<#IMG_DIR#>/p_yim.gif\' border=\'0\' alt=\'Yahoo\'>',1,11),
(872,'P_ICQ','<img src=\'<#IMG_DIR#>/p_icq.gif\' border=\'0\'  alt=\'ICQ\'>',1,11),
(873,'P_MSG','<img src=\'<#IMG_DIR#>/p_pm.gif\' border=\'0\'  alt=\'PM\'>',1,11),
(874,'P_EMAIL','<img src=\'<#IMG_DIR#>/p_email.gif\' border=\'0\'  alt=\'Email Poster\'>',1,11),
(875,'P_EDIT','<img src=\'<#IMG_DIR#>/p_edit.gif\' border=\'0\'  alt=\'Edit Post\'>',1,11),
(876,'P_DELETE','<img src=\'<#IMG_DIR#>/p_delete.gif\' border=\'0\'  alt=\'Delete Post\'>',1,11),
(877,'P_AOL','<img src=\'<#IMG_DIR#>/p_aim.gif\' border=\'0\'  alt=\'AOL\'>',1,11),
(878,'F_NAV_SEP','&nbsp;-&gt;&nbsp;',1,11),
(879,'M_UNREAD','<img src=\'<#IMG_DIR#>/f_norm.gif\' border=\'0\'  alt=\'Есть новые. Добавить в Избранное.\'>',1,11),
(880,'F_NAV','<img src=\'<#IMG_DIR#>/nav.gif\' border=\'0\'  alt=\'&gt;\'>',1,11),
(881,'F_STATS','<a href=\'http://forum.sources.ru/index.php?act=Help&CODE=01&HID=21\'><img src=\'<#IMG_DIR#>/stats.gif\' border=\'0\'  alt=\'Board Stats\'></a>',1,11),
(882,'C_ON_CAT','<img src=\'<#IMG_DIR#>/bc_new.gif\' border=\'0\'  alt=\'New Posts\'>',1,11),
(883,'C_ON','<img src=\'<#IMG_DIR#>/bf_new.gif\' border=\'0\'  alt=\'New Posts\'>',1,11),
(884,'C_OFF','<img src=\'<#IMG_DIR#>/bf_nonew.gif\' border=\'0\'  alt=\'No New Posts\'>',1,11),
(885,'C_OFF_CAT','<img src=\'<#IMG_DIR#>/bc_nonew.gif\' border=\'0\'  alt=\'No New Posts\'>',1,11),
(886,'C_LOCKED','<img src=\'<#IMG_DIR#>/bf_readonly.gif\' border=\'0\'  alt=\'Премодерация\'>',1,11),
(887,'B_POLL_NN_DOT','<img src=\'<#IMG_DIR#>/f_poll_no_dot.gif\' border=\'0\' alt=\'Нет новых голосов. Добавить в Избранное.\'>',1,11),
(888,'B_NEW_DOT','<img src=\'<#IMG_DIR#>/f_norm_dot.gif\' border=\'0\' alt=\'Нет новых. Добавить в Избранное.\'>',1,11),
(889,'B_HOT_DOT','<img src=\'<#IMG_DIR#>/f_hot_dot.gif\' border=\'0\' alt=\'Есть новые. Добавить в Избранное.\'>',1,11),
(890,'B_POLL_NN','<img src=\'<#IMG_DIR#>/f_poll_no.gif\' border=\'0\'  alt=\'Нет новых голосов. Добавить в Избранное.\'>',1,11),
(891,'B_POLL','<img src=\'<#IMG_DIR#>/f_poll.gif\' border=\'0\'  alt=\'Есть новые голоса. Добавить в Избранное.\'>',1,11),
(892,'B_PIN','<img src=\'<#IMG_DIR#>/f_pinned.gif\' border=\'0\'  alt=\'Pinned\'>',1,11),
(893,'B_NORM','<img src=\'<#IMG_DIR#>/f_norm_no.gif\' border=\'0\'  alt=\'Нет новых. Добавить в Избранное.\'>',1,11),
(894,'B_NEW','<img src=\'<#IMG_DIR#>/f_norm.gif\' border=\'0\'  alt=\'Есть новые. Добавить в Избранное.\'>',1,11),
(895,'C_ON_RES','<img src=\'<#IMG_DIR#>/br_new.gif\' border=\'0\'  alt=\'New Posts\' >',1,11),
(896,'F_ACTIVE','<img src=\'<#IMG_DIR#>/user.gif\' border=\'0\'  alt=\'Active Users\'>',1,11),
(897,'M_READ','<img src=\'<#IMG_DIR#>/f_norm_no.gif\' border=\'0\'  alt=\'Есть новые. Добавить в Избранное.\'>',1,11),
(898,'CAMERA','<img src=\'<#IMG_DIR#>/camera.gif\' border=\'0\'  alt=\'Photo\'>',1,11),
(899,'NO_PHOTO','<img src=\'<#IMG_DIR#>/nophoto.gif\' border=\'0\'  alt=\'No Photo\'>',1,11),
(900,'B_LOCKED','<img src=\'<#IMG_DIR#>/f_closed.gif\' border=\'0\'  alt=\'Закрыта. Добавить в Избранное.\'>',1,11),
(901,'C_OFF_RES','<img src=\'<#IMG_DIR#>/br_nonew.gif\' border=\'0\'  alt=\'No New Posts\'>',1,11),
(902,'B_HOT_NN','<img src=\'<#IMG_DIR#>/f_hot_no.gif\' border=\'0\'  alt=\'Нет новых. Добавить в Избранное.\'>',1,11),
(903,'WARN_1','<img src=\'<#IMG_DIR#>/warn1.gif\' border=\'0\'  alt=\'X----\'>',1,12),
(904,'WARN_0','<img src=\'<#IMG_DIR#>/warn0.gif\' border=\'0\'  alt=\'-----\'>',1,12),
(905,'WARN_2','<img src=\'<#IMG_DIR#>/warn2.gif\' border=\'0\'  alt=\'XX---\'>',1,12),
(906,'F_RULES','<img src=\'<#IMG_DIR#>/forum_rules.gif\' border=\'0\'  alt=\'!\'>',1,12),
(907,'CAL_NEWEVENT','<img src=\'<#IMG_DIR#>/cal_newevent.gif\' border=\'0\'  alt=\'Добавить новое\'>',1,12),
(908,'T_QREPLY','Быстрый ответ',1,12),
(909,'T_OPTS','<img src=\'<#IMG_DIR#>/t_options.gif\' border=\'0\'  alt=\'Опции темы\'>',1,12),
(910,'ADDRESS_CARD','<img src=\'<#IMG_DIR#>/addresscard.gif\' border=\'0\'  alt=\'Профиль\'>',1,12),
(911,'INTEGRITY_MSGR','<img src=\'<#IMG_DIR#>/p_im.gif\' border=\'0\'  alt=\'IM\'>',1,12),
(912,'BR_REDIRECT','<img src=\'<#IMG_DIR#>/br_redirect.gif\' border=\'0\'  alt=\'Ссылка\'>',1,12),
(913,'LAST_POST','<img src=\'<#IMG_DIR#>/lastpost.gif\' border=\'0\'  alt=\'Последнее\'>',1,12),
(914,'NEW_POST','<img src=\'<#IMG_DIR#>/new.gif\' border=\'0\'  alt=\'Новое\' title=\'Новое\' hspace=2>',1,12),
(915,'CAT_IMG','<img src=\'<#IMG_DIR#>/nav_m.gif\' border=\'0\'  alt=\'>\'>',1,12),
(916,'P_REPORT','Позвать модератора',1,12),
(917,'P_MSN','<img src=\'<#IMG_DIR#>/p_msn.gif\' border=\'0\' alt=\'MSN\'>',1,12),
(918,'P_YIM','<img src=\'<#IMG_DIR#>/p_yim.gif\' border=\'0\' alt=\'Yahoo\'>',1,12),
(919,'P_QUOTE','Цитата',1,12),
(920,'P_WEBSITE','<img src=\'<#IMG_DIR#>/p_www.gif\' border=\'0\'  alt=\'Сайт\'>',1,12),
(921,'P_MSG','<img src=\'<#IMG_DIR#>/p_pm.gif\' border=\'0\'  alt=\'Перс. сообщ.\'>',1,12),
(922,'P_ICQ','<img src=\'<#IMG_DIR#>/p_icq.gif\' border=\'0\'  alt=\'ICQ\'>',1,12),
(923,'P_EMAIL','<img src=\'<#IMG_DIR#>/p_email.gif\' border=\'0\'  alt=\'Мыло\'>',1,12),
(924,'P_DELETE','Удалить',1,12),
(925,'P_EDIT','Изменить',1,12),
(926,'P_AOL','<img src=\'<#IMG_DIR#>/p_aim.gif\' border=\'0\'  alt=\'AOL\'>',1,12),
(927,'M_UNREAD','<img src=\'<#IMG_DIR#>/f_norm.gif\' border=\'0\'  alt=\'Есть новые\'>',1,12),
(928,'M_READ','<img src=\'<#IMG_DIR#>/f_norm_no.gif\' border=\'0\'  alt=\'Нет новых.\'>',1,12),
(929,'CAMERA','<img src=\'<#IMG_DIR#>/camera.gif\' border=\'0\'  alt=\'Фото\'>',1,12),
(930,'NO_PHOTO','<img src=\'<#IMG_DIR#>/nophoto.gif\' border=\'0\'  alt=\'Нет фотографии\'>',1,12),
(931,'F_STATS','<a href=\'http://forum.sources.ru/index.php?act=Help&CODE=01&HID=21\'><img src=\'<#IMG_DIR#>/stats.gif\' border=\'0\'  alt=\'Статистика\'></a>',1,12),
(932,'F_NAV','<img src=\'<#IMG_DIR#>/nav.gif\' border=\'0\'  alt=\'&gt;\'>',1,12),
(933,'F_NAV_SEP','<img src=\'<#IMG_DIR#>/open.gif\' border=\'0\'  alt=\'\'>&nbsp;&nbsp;',1,12),
(934,'F_ACTIVE','<img src=\'<#IMG_DIR#>/user.gif\' border=\'0\'  alt=\'Участники\'>',1,12),
(935,'C_ON_RES','<img src=\'<#IMG_DIR#>/br_new.gif\' border=\'0\'  alt=\'Есть новые\' >',1,12),
(936,'C_ON_CAT','<img src=\'<#IMG_DIR#>/bc_new.gif\' border=\'0\'  alt=\'Есть новые\'>',1,12),
(937,'C_ON','<img src=\'<#IMG_DIR#>/bf_new.gif\' border=\'0\'  alt=\'Есть новые\'>',1,12),
(938,'C_OFF_RES','<img src=\'<#IMG_DIR#>/br_nonew.gif\' border=\'0\'  alt=\'Нет новых\'>',1,12),
(939,'C_OFF_CAT','<img src=\'<#IMG_DIR#>/bc_nonew.gif\' border=\'0\'  alt=\'Нет новых\'>',1,12),
(940,'C_OFF','<img src=\'<#IMG_DIR#>/bf_nonew.gif\' border=\'0\'  alt=\'Нет новых\'>',1,12),
(941,'C_LOCKED','<img src=\'<#IMG_DIR#>/bf_readonly.gif\' border=\'0\'  alt=\'Премодерация\'>',1,12),
(942,'B_POLL_NN_DOT','<img src=\'<#IMG_DIR#>/f_poll_no_dot.gif\' border=\'0\' alt=\'Нет новых голосов.\'>',1,12),
(943,'B_POLL_DOT','<img src=\'<#IMG_DIR#>/f_poll_dot.gif\' border=\'0\' alt=\'Есть новые голоса.\'>',1,12),
(944,'B_NORM_DOT','<img src=\'<#IMG_DIR#>/f_norm_no_dot.gif\' border=\'0\' alt=\'Нет новых\'>',1,12),
(945,'B_HOT_NN_DOT','<img src=\'<#IMG_DIR#>/f_hot_no_dot.gif\' border=\'0\' alt=\'Нет новых\'>',1,12),
(946,'B_NEW_DOT','<img src=\'<#IMG_DIR#>/f_norm_dot.gif\' border=\'0\' alt=\'Есть новые\'>',1,12),
(947,'B_HOT_DOT','<img src=\'<#IMG_DIR#>/f_hot_dot.gif\' border=\'0\' alt=\'Есть новые\'>',1,12),
(948,'B_POLL_NN','<img src=\'<#IMG_DIR#>/f_poll_no.gif\' border=\'0\'  alt=\'Нет новых голосов.\'>',1,12),
(949,'B_POLL','<img src=\'<#IMG_DIR#>/f_poll.gif\' border=\'0\'  alt=\'Есть новые голоса.\'>',1,12),
(950,'B_PIN','<img src=\'<#IMG_DIR#>/f_pinned.gif\' border=\'0\'  alt=\'Важный\'>',1,12),
(951,'B_NORM','<img src=\'<#IMG_DIR#>/f_norm_no.gif\' border=\'0\'  alt=\'Нет новых.\'>',1,12),
(952,'B_NEW','<img src=\'<#IMG_DIR#>/f_norm.gif\' border=\'0\'  alt=\'Есть новые\'>',1,12),
(953,'B_MOVED','<img src=\'<#IMG_DIR#>/f_moved.gif\' border=\'0\'  alt=\'Перемещена.\'>',1,12),
(954,'B_LOCKED','<img src=\'<#IMG_DIR#>/f_closed.gif\' border=\'0\'  alt=\'Закрыта.\'>',1,12),
(955,'B_HOT_NN','<img src=\'<#IMG_DIR#>/f_hot_no.gif\' border=\'0\'  alt=\'Нет новых.\'>',1,12),
(956,'B_HOT','<img src=\'<#IMG_DIR#>/f_hot.gif\' border=\'0\'  alt=\'Горячая тема.\'>',1,12),
(957,'A_POLL','Новое голосование',1,12),
(958,'A_STAR','<img src=\'<#IMG_DIR#>/pip.gif\' border=\'0\'  alt=\'*\'>',1,12),
(959,'A_POST','Новая тема',1,12),
(960,'A_REPLY','Ответить',1,12),
(961,'A_POLLONLY_B','<font color=gray>закрыто</font>',1,12),
(962,'A_MOVED_B','<font color=gray>перемещена</font>',1,12),
(963,'A_LOCKED_B','<font color=gray>закрыта</font>',1,12),
(964,'WARN_3','<img src=\'<#IMG_DIR#>/warn3.gif\' border=\'0\'  alt=\'XXX--\'>',1,12),
(965,'WARN_4','<img src=\'<#IMG_DIR#>/warn4.gif\' border=\'0\'  alt=\'XXXX-\'>',1,12),
(966,'WARN_5','<img src=\'<#IMG_DIR#>/warn5.gif\' border=\'0\'  alt=\'XXXXX\'>',1,12),
(967,'WARN_ADD','<img src=\'<#IMG_DIR#>/warn_add.gif\' border=\'0\'  alt=\'+\'>',1,12),
(968,'WARN_MINUS','<img src=\'<#IMG_DIR#>/warn_minus.gif\' border=\'0\'  alt=\'-\'>',1,12),
(1423,'C_MINUS','<img src=\'<#IMG_DIR#>/minimize.gif\' border=\'0\' alt=\' - \'>',1,12),
(1422,'C_PLUS','<img src=\'<#IMG_DIR#>/maximize.gif\' border=\'0\' alt=\' + \'>',1,12),
(971,'REP_ADD','<img src=\'<#IMG_DIR#>/rep_plus.gif\' border=\'0\' alt=\'+\'>',1,12),
(972,'REP_MINUS','<img src=\'<#IMG_DIR#>/rep_minus.gif\' border=\'0\'  alt=\'-\'>',1,12),
(973,'REP_UP','<img src=\'<#IMG_DIR#>/rep_up.gif\' border=\'0\'  alt=\'+\'>',1,12),
(974,'REP_DOWN','<img src=\'<#IMG_DIR#>/rep_down.gif\' border=\'0\'  alt=\'-\'>',1,12),
(975,'shadowL','<img src=\'<#IMG_DIR#>/left_shadow.gif\' border=\'0\'>',1,13),
(976,'shadowR','<img src=\'<#IMG_DIR#>/right_shadow.gif\' border=\'0\'>',1,13),
(977,'shadowCL','<img src=\'<#IMG_DIR#>/cat_left_shadow.gif\' border=\'0\'>',1,13),
(978,'mem_left','<img src=\"<#IMG_DIR#>/mem_left.gif\"  border=\"0\">',1,13),
(979,'mem_right','<img src=\"<#IMG_DIR#>/mem_right.gif\"  border=\"0\">',1,13),
(980,'M_CAL','<img src=\'<#IMG_DIR#>/icon_clndr.gif\' border=\'0\' style=\'vertical-align: top;\'>',1,13),
(981,'M_MEM','<img src=\'<#IMG_DIR#>/icon_members.gif\' border=\'0\' style=\'vertical-align: top;\'>',1,13),
(982,'M_HELP','<img src=\'<#IMG_DIR#>/icon_help.gif\' border=\'0\' style=\'vertical-align: top;\'>',1,13),
(983,'M_SEARCH','<img src=\'<#IMG_DIR#>/icon_search.gif\' border=\'0\' style=\'vertical-align: top;\'>',1,13),
(984,'WARN_MINUS','<img src=\'<#IMG_DIR#>/warn_minus.gif\' border=\'0\'  alt=\'-\'>',1,13),
(985,'WARN_ADD','<img src=\'<#IMG_DIR#>/warn_add.gif\' border=\'0\'  alt=\'+\'>',1,13),
(986,'WARN_5','<img src=\'<#IMG_DIR#>/warn5.gif\' border=\'0\'  alt=\'XXXXX\'>',1,13),
(987,'WARN_4','<img src=\'<#IMG_DIR#>/warn4.gif\' border=\'0\'  alt=\'XXXX-\'>',1,13),
(988,'WARN_3','<img src=\'<#IMG_DIR#>/warn3.gif\' border=\'0\'  alt=\'XXX--\'>',1,13),
(989,'WARN_2','<img src=\'<#IMG_DIR#>/warn2.gif\' border=\'0\'  alt=\'XX---\'>',1,13),
(990,'WARN_1','<img src=\'<#IMG_DIR#>/warn1.gif\' border=\'0\'  alt=\'X----\'>',1,13),
(991,'WARN_0','<img src=\'<#IMG_DIR#>/warn0.gif\' border=\'0\'  alt=\'-----\'>',1,13),
(992,'F_RULES','<img src=\'<#IMG_DIR#>/forum_rules.gif\' border=\'0\'  alt=\'Forum Rules\'>',1,13),
(993,'CAL_NEWEVENT','<img src=\'<#IMG_DIR#>/cal_newevent.gif\' border=\'0\'  alt=\'Add New Event\'>',1,13),
(994,'T_OPTS','<img src=\'<#IMG_DIR#>/t_options.gif\' border=\'0\'  alt=\'Topic Options\'>',1,13),
(995,'T_QREPLY','<img src=\'<#IMG_DIR#>/t_qr.gif\' border=\'0\'  alt=\'Quick Reply\'>',1,13),
(996,'ADDRESS_CARD','<img src=\'<#IMG_DIR#>/addresscard.gif\' border=\'0\'  alt=\'Mini Profile\'>',1,13),
(997,'INTEGRITY_MSGR','<img src=\'<#IMG_DIR#>/p_im.gif\' border=\'0\'  alt=\'Integrity Messenger IM\'>',1,13),
(998,'BR_REDIRECT','<img src=\'<#IMG_DIR#>/br_redirect.gif\' border=\'0\'  alt=\'Redirect\'>',1,13),
(999,'LAST_POST','<img src=\'<#IMG_DIR#>/lastpost.gif\' border=\'0\'  alt=\'Last Post\'>',1,13),
(1000,'NEW_POST','<img src=\'<#IMG_DIR#>/newpost.gif\' border=\'0\'  alt=\'Goto last unread\' title=\'Goto last unread\' hspace=2>',1,13),
(1001,'CAT_IMG','<img src=\'<#IMG_DIR#>/nav_m.gif\' border=\'0\'  alt=\'&gt;\' width=\'8\' height=\'8\'>',1,13),
(1002,'P_MSN','<img src=\'<#IMG_DIR#>/p_msn.gif\' border=\'0\' alt=\'MSN\'>',1,13),
(1003,'P_REPORT','<img src=\'<#IMG_DIR#>/p_report.gif\' border=\'0\'  alt=\'Report Post\'  style=\'vertical-align: middle;\'/>',1,13),
(1004,'P_YIM','<img src=\'<#IMG_DIR#>/p_yim.gif\' border=\'0\' alt=\'Yahoo\'>',1,13),
(1005,'P_WEBSITE','<img src=\'<#IMG_DIR#>/p_www.gif\' border=\'0\'  alt=\'Users Website\'>',1,13),
(1006,'P_QUOTE','<img src=\'<#IMG_DIR#>/p_quote.gif\' border=\'0\'  alt=\'Quote Post\'  style=\'vertical-align: middle;\'/>',1,13),
(1007,'P_MSG','<img src=\'<#IMG_DIR#>/p_pm.gif\' border=\'0\'  alt=\'PM\'>',1,13),
(1008,'P_EMAIL','<img src=\'<#IMG_DIR#>/p_email.gif\' border=\'0\'  alt=\'Email Poster\'>',1,13),
(1009,'P_ICQ','<img src=\'<#IMG_DIR#>/p_icq.gif\' border=\'0\'  alt=\'ICQ\'>',1,13),
(1010,'P_EDIT','<img src=\'<#IMG_DIR#>/p_edit.gif\' border=\'0\'  alt=\'Edit Post\'  style=\'vertical-align: middle;\'/>',1,13),
(1011,'P_DELETE','<img src=\'<#IMG_DIR#>/p_delete.gif\' border=\'0\'  alt=\'Delete Post\' style=\'vertical-align: middle;\'>',1,13),
(1012,'P_AOL','<img src=\'<#IMG_DIR#>/p_aim.gif\' border=\'0\'  alt=\'AOL\'>',1,13),
(1013,'A_LOCKED_B','<img src=\'<#IMG_DIR#>/t_closed.gif\' border=\'0\'  alt=\'Closed Topic\'>',1,13),
(1014,'A_POLLONLY_B','<img src=\'<#IMG_DIR#>/t_closed.gif\' border=\'0\'  alt=\'Poll Only\'>',1,13),
(1015,'A_MOVED_B','<img src=\'<#IMG_DIR#>/t_moved.gif\' border=\'0\'  alt=\'Moved Topic\'>',1,13),
(1016,'A_POST','<img src=\'<#IMG_DIR#>/t_new.gif\' border=\'0\'  alt=\'Start new topic\'>',1,13),
(1017,'A_REPLY','<img src=\'<#IMG_DIR#>/t_reply.gif\' border=\'0\'  alt=\'Reply to this topic\'>',1,13),
(1018,'A_POLL','<img src=\'<#IMG_DIR#>/t_poll.gif\' border=\'0\'  alt=\'Start Poll\'>',1,13),
(1019,'A_STAR','<img src=\'<#IMG_DIR#>/pip.gif\' border=\'0\'  alt=\'*\'>',1,13),
(1020,'B_HOT_NN','<img src=\'<#IMG_DIR#>/f_hot_no.gif\' border=\'0\'  alt=\'Нет новых. Добавить в Избранное.\'>',1,13),
(1021,'B_HOT','<img src=\'<#IMG_DIR#>/f_hot.gif\' border=\'0\'  alt=\'Горячая тема. Добавить в Избранное.\'>',1,13),
(1022,'B_LOCKED','<img src=\'<#IMG_DIR#>/f_closed.gif\' border=\'0\'  alt=\'Закрыта. Добавить в Избранное.\'>',1,13),
(1023,'B_NEW','<img src=\'<#IMG_DIR#>/f_norm.gif\' border=\'0\'  alt=\'Есть новые. Добавить в Избранное.\'>',1,13),
(1024,'B_MOVED','<img src=\'<#IMG_DIR#>/f_moved.gif\' border=\'0\'  alt=\'Перемещена. Добавить в Избранное.\'>',1,13),
(1025,'B_NORM','<img src=\'<#IMG_DIR#>/f_norm_no.gif\' border=\'0\'  alt=\'Нет новых. Добавить в Избранное.\'>',1,13),
(1026,'B_PIN','<img src=\'<#IMG_DIR#>/f_pinned.gif\' border=\'0\'  alt=\'Важная.\'>',1,13),
(1027,'B_POLL','<img src=\'<#IMG_DIR#>/f_poll.gif\' border=\'0\'  alt=\'Голосование\'>',1,13),
(1028,'shadowCR','<img src=\'<#IMG_DIR#>/cat_right_shadow.gif\' border=\'0\'>',1,13),
(1029,'B_POLL_NN','<img src=\'<#IMG_DIR#>/f_poll_no.gif\' border=\'0\'  alt=\'Нет новых голосов. Добавить в Избранное.\'>',1,13),
(1030,'B_HOT_DOT','<img src=\'<#IMG_DIR#>/f_hot_dot.gif\' border=\'0\' alt=\'Нет новых. Добавить в Избранное.\'>',1,13),
(1031,'B_NEW_DOT','<img src=\'<#IMG_DIR#>/f_norm_dot.gif\' border=\'0\' alt=\'Нет новых. Добавить в Избранное.\'>',1,13),
(1032,'B_HOT_NN_DOT','<img src=\'<#IMG_DIR#>/f_hot_no_dot.gif\' border=\'0\' alt=\'Нет новых. Добавить в Избранное.\'>',1,13),
(1033,'B_NORM_DOT','<img src=\'<#IMG_DIR#>/f_norm_no_dot.gif\' border=\'0\' alt=\'Нет новых. Добавить в Избранное.\'>',1,13),
(1034,'acp','<img src=\'<#IMG_DIR#>/mem_acp.gif\' border=\'0\'  alt=\'\' style=\'vertical-align:top;\'/>',1,13),
(1035,'mcp','<img src=\'<#IMG_DIR#>/mem_mcp.gif\' border=\'0\'  alt=\'\'  style=\'vertical-align: top\'/>',1,13),
(1036,'ucp','<img src=\'<#IMG_DIR#>/mem_ucp.gif\' border=\'0\'  alt=\'\' style=\'vertical-align: top\'>',1,13),
(1037,'ass','<img src=\'<#IMG_DIR#>/mem_ass.gif\' border=\'0\'  alt=\'\'  style=\'vertical-align: top\'/>',1,13),
(1038,'lo','<img src=\'<#IMG_DIR#>/mem_lo.gif\' border=\'0\'  style=\'vertical-align: top\'>',1,13),
(1039,'li','<img src=\'<#IMG_DIR#>/mem_li.gif\' border=\'0\'  alt=\'\' style=\'vertical-align: top\'>',1,13),
(1040,'np','<img src=\'<#IMG_DIR#>/mem_np.gif\' border=\'0\'  alt=\'\'  style=\'vertical-align: top\'/>',1,13),
(1041,'rv','<img src=\'<#IMG_DIR#>/mem_rv.gif\' border=\'0\'  alt=\'\'  style=\'vertical-align: top\'/>',1,13),
(1042,'reg','<img src=\'<#IMG_DIR#>/mem_reg.gif\' border=\'0\'  alt=\'\' style=\'vertical-align: top\'>',1,13),
(1043,'brules','<img src=\'<#IMG_DIR#>/mem_rules.gif\' border=\'0\' style=\'vertical-align: top;\'/>',1,13),
(1044,'home','<img src=\'<#IMG_DIR#>/mem_home.gif\' border=\'0\'  style=\'vertical-align: top;\'>',1,13),
(1045,'logo','<img src=\'<#IMG_DIR#>/logo.gif\' border=\'0\'  style=\'vertical-align: middle\'>',1,13),
(1046,'maintspace','<img src=\'<#IMG_DIR#>/spacer.gif\' border=\'0\'  alt=\'\' style=\'vertical-align:middle;\' height=\'20\' width=\'1\'/>',1,13),
(1047,'tmspace','<img src=\'<#IMG_DIR#>/spacer.gif\' border=\'0\'  alt=\'\' style=\'vertical-align:middle;\' height=\'17\' width=\'1\'/>',1,13),
(1048,'msg_ffw','<img src=\'<#IMG_DIR#>/m_forward.gif\' border=\'0\'  alt=\'Forward this PM\'>',1,13),
(1049,'msg_reply','<img src=\'<#IMG_DIR#>/msg_l_reply.gif\' border=\'0\'  alt=\'Reply to this PM\'>',1,13),
(1050,'addbud','<img src=\'<#IMG_DIR#>/msg_l_addmem.gif\' border=\'0\'  alt=\'Reply to this PM\'>',1,13),
(1051,'down','<img src=\'<#IMG_DIR#>/p_down.gif\' border=\'0\'  alt=\'Jump to Bottom\'>',1,13),
(1052,'A_STATS','<img src=\'<#IMG_DIR#>/stats.gif\' border=\'0\'  alt=\'Statistics\'>',1,13),
(1053,'A_CAL','<img src=\'<#IMG_DIR#>/calendar.gif\' border=\'0\'  alt=\'calendar\'>',1,13),
(1054,'A_BIRTH','<img src=\'<#IMG_DIR#>/birthday.gif\' border=\'0\'  alt=\'Birthdays\'>',1,13),
(1055,'shadowMR','<img src=\'<#IMG_DIR#>/mainfoot_right_shadow.gif\' border=\'0\'>',1,13),
(1056,'shadowML','<img src=\'<#IMG_DIR#>/mainfoot_left_shadow.gif\' border=\'0\'>',1,13),
(1057,'M_UNREAD','<img src=\'<#IMG_DIR#>/f_norm.gif\' border=\'0\'  alt=\'Есть новые. Добавить в Избранное.\'>',1,13),
(1058,'M_READ','<img src=\'<#IMG_DIR#>/f_norm_no.gif\' border=\'0\'  alt=\'Есть новые. Добавить в Избранное.\'>',1,13),
(1059,'CAMERA','<img src=\'<#IMG_DIR#>/camera.gif\' border=\'0\'  alt=\'Photo\'>',1,13),
(1060,'NO_PHOTO','<img src=\'<#IMG_DIR#>/nophoto.gif\' border=\'0\'  alt=\'No Photo\'>',1,13),
(1061,'F_STATS','<a href=\'http://forum.sources.ru/index.php?act=Help&CODE=01&HID=21\'><img src=\'<#IMG_DIR#>/stats.gif\' border=\'0\'  alt=\'Board Stats\'></a>',1,13),
(1062,'F_NAV','<img src=\'<#IMG_DIR#>/nav.gif\' border=\'0\'  alt=\'>\' style=\'vertical-align: middle;\'/>',1,13),
(1063,'F_NAV_SEP','&nbsp;-&gt;&nbsp;',1,13),
(1064,'F_ACTIVE','<img src=\'<#IMG_DIR#>/user.gif\' border=\'0\'  alt=\'Active Users\'>',1,13),
(1065,'C_ON_RES','<img src=\'<#IMG_DIR#>/br_new.gif\' border=\'0\'  alt=\'New Posts\' >',1,13),
(1066,'C_ON_CAT','<img src=\'<#IMG_DIR#>/bc_new.gif\' border=\'0\'  alt=\'New Posts\'>',1,13),
(1067,'C_ON','<img src=\'<#IMG_DIR#>/bf_new.gif\' border=\'0\'  alt=\'New Posts\'>',1,13),
(1068,'B_POLL_DOT','<img src=\'<#IMG_DIR#>/f_poll_dot.gif\' border=\'0\' alt=\'Нет новыых голосов. Добавить в Избранное.\'>',1,13),
(1069,'B_POLL_NN_DOT','<img src=\'<#IMG_DIR#>/f_poll_no_dot.gif\' border=\'0\' alt=\'Нет новых голосов. Добавить в Избранное.\'>',1,13),
(1070,'C_LOCKED','<img src=\'<#IMG_DIR#>/bf_readonly.gif\' border=\'0\'  alt=\'Премодерация\'>',1,13),
(1071,'C_OFF','<img src=\'<#IMG_DIR#>/bf_nonew.gif\' border=\'0\'  alt=\'No New Posts\'>',1,13),
(1072,'C_OFF_CAT','<img src=\'<#IMG_DIR#>/bc_nonew.gif\' border=\'0\'  alt=\'No New Posts\'>',1,13),
(1073,'C_OFF_RES','<img src=\'<#IMG_DIR#>/br_nonew.gif\' border=\'0\'  alt=\'No New Posts\'>',1,13),
(1431,'C_MINUS','<img src=\'<#IMG_DIR#>/minimize.gif\' border=\'0\' alt=\' - \'>',1,13),
(1430,'C_PLUS','<img src=\'<#IMG_DIR#>/maximize.gif\' border=\'0\' alt=\' + \'>',1,13),
(1076,'REP_ADD','<img src=\'<#IMG_DIR#>/rep_plus.gif\' border=\'0\'  alt=\'+\'>',1,13),
(1077,'REP_MINUS','<img src=\'<#IMG_DIR#>/rep_minus.gif\' border=\'0\'  alt=\'-\'>',1,13),
(1078,'REP_UP','<img src=\'<#IMG_DIR#>/rep_up.gif\' border=\'0\'  alt=\'+\'>',1,13),
(1079,'REP_DOWN','<img src=\'<#IMG_DIR#>/rep_down.gif\' border=\'0\'  alt=\'-\'>',1,13),
(1574,'RSS','<a href=\"index.php?showtopic=81342\"><img src=\'<#IMG_DIR#>/rss.gif\' border=\'0\'  alt=\'RSS\'> RSS</a>\r\n',1,11),
(1575,'RSS','<a href=\"index.php?showtopic=81342\"><img src=\'<#IMG_DIR#>/rss.gif\' border=\'0\'  alt=\'RSS\'> RSS</a>\r\n',1,12),
(1576,'RSS','·&nbsp;&nbsp;<a style=\"border:1px solid;border-color:#ffc8a4 #7d3302 #3f1a01 #ff9a57; padding:0px 3px 0px 3px; font:bold 10px verdana,sans-serif; color:#FFFFFF; background-color:#ff6600; text-decoration:none; margin:0px; vertical-align:middle;\" href=\"index.php?showtopic=81342\">RSS</a>\r\n',1,16),
(1577,'RSS','<a href=\"index.php?showtopic=81342\"><img src=\'<#IMG_DIR#>/rss.gif\' border=\'0\'  alt=\'RSS\'> RSS</a>',1,17),
(1578,'RSS','<a href=\"index.php?showtopic=81342\"><img src=\'<#IMG_DIR#>/rss.gif\' border=\'0\'  alt=\'RSS\'> RSS</a>\r\n',1,13),
(1579,'P_X','X',1,11),
(1580,'P_X','X',1,12),
(1581,'P_X','X',1,13),
(1582,'P_X','X',1,17),
(1583,'P_X','X',1,16),
(1584,'A_DECIDED','<b>Вопрос решён</b>',1,16),
(1585,'B_DECIDED','<font size=\'+1\' color=\'green\'><b>&#8730;</b></font>',1,16),
(1586,'C_DECIDED','Вопрос не решён',1,16),
(1587,'A_DECIDED','<b>Вопрос решён</b>',1,11),
(1588,'C_DECIDED','Вопрос не решён',1,11),
(1589,'B_DECIDED','<img src=\'<#IMG_DIR#>/f_decided.gif\' border=\'0\'  alt=\'Решён\'>',1,11),
(1590,'A_DECIDED','<b>Вопрос решён</b>',1,12),
(1591,'B_DECIDED','<img src=\'<#IMG_DIR#>/f_decided.gif\' border=\'0\'  alt=\'Решён\'>',1,12),
(1592,'C_DECIDED','Вопрос не решён',1,12),
(1593,'B_DECIDED','<img src=\'<#IMG_DIR#>/f_decided.gif\' border=\'0\'  alt=\'Решён\'>',1,13),
(1594,'C_DECIDED','Вопрос не решён',1,13),
(1595,'A_DECIDED','<b>Вопрос решён</b>',1,13),
(1596,'B_DECIDED','<img src=\'<#IMG_DIR#>/f_decided.gif\' border=\'0\'  alt=\'Решён\'>',1,17),
(1597,'C_DECIDED','Вопрос не решён',1,17),
(1598,'A_DECIDED','<b>Вопрос решён</b>',1,17),
(1599,'P_FAQ_ADD','В FAQ',1,16),
(1600,'P_FAQ_EXISTS','<font color=gray>Добавлено в FAQ</font>',1,16),
(1601,'P_FAQ_EXISTS','<font color=gray>Добавлено в FAQ</font>',1,11),
(1602,'P_FAQ_ADD','В FAQ',1,11),
(1603,'P_FAQ_EXISTS','<font color=gray>Добавлено в FAQ</font>',1,12),
(1604,'P_FAQ_ADD','В FAQ',1,12),
(1605,'P_FAQ_EXISTS','<font color=gray>Добавлено в FAQ</font>',1,13),
(1606,'P_FAQ_ADD','В FAQ',1,13),
(1607,'P_FAQ_EXISTS','<font color=gray>Добавлено в FAQ</font>',1,17),
(1608,'P_FAQ_ADD','В FAQ',1,17),
(1609,'P_DELETED','<span class=\'movedprefix\'>Удалено</span>',1,16),
(1610,'P_DELETED','<span class=\'movedprefix\'>Удалено</span>',1,11),
(1611,'P_DELETED','<span class=\'movedprefix\'>Удалено</span>',1,12),
(1612,'P_DELETED','<span class=\'movedprefix\'>Удалено</span>',1,13),
(1613,'P_DELETED','<span class=\'movedprefix\'>Удалено</span>',1,17),
(1614,'atb_faq','<img src=\"<#IMG_DIR#>/atb_faq.gif\" border=\"\" alt=\"\">',1,11),
(1615,'atb_faq','<img src=\"<#IMG_DIR#>/atb_faq.gif\" border=\"\" alt=\"\">',1,12),
(1616,'atb_faq','<img src=\"<#IMG_DIR#>/atb_faq.gif\" border=\"\" alt=\"\">',1,13),
(1617,'atb_faq','<img src=\"<#IMG_DIR#>/atb_faq.gif\" border=\"\" alt=\"\">',1,17),
(1618,'atb_faq','',1,16),
(1619,'B_MIRRORED','<img src=\'<#IMG_DIR#>/f_mirrored.gif\' border=\'0\' alt=\'Зеркальная тема\'>',1,11),
(1620,'B_MIRRORED','<img src=\'<#IMG_DIR#>/f_mirrored.gif\' border=\'0\' alt=\'Зеркальная тема\'>',1,12),
(1621,'B_MIRRORED','<img src=\'<#IMG_DIR#>/f_mirrored.gif\' border=\'0\' alt=\'Зеркальная тема\'>',1,13),
(1622,'B_MIRRORED','<font title=\'Зеркальная тема\' size=\'+1\' color=\'88A0C0\'><b>&#9632;</b></font>',1,16),
(1623,'B_MIRRORED','<img src=\'<#IMG_DIR#>/f_mirrored.gif\' border=\'0\' alt=\'Зеркальная тема\'>',1,17),
(1624,'B_MIRRORED_NO','<img src=\'<#IMG_DIR#>/f_mirrored_no.gif\' border=\'0\' alt=\'Зеркальная тема, нет новых сообщений\'>',1,11),
(1625,'B_MIRRORED_NO','<img src=\'<#IMG_DIR#>/f_mirrored_no.gif\' border=\'0\' alt=\'Зеркальная тема, нет новых сообщений\'>',1,12),
(1626,'B_MIRRORED_NO','<img src=\'<#IMG_DIR#>/f_mirrored_no.gif\' border=\'0\' alt=\'Зеркальная тема, нет новых сообщений\'>',1,13),
(1627,'B_MIRRORED_NO','<font title=\'Зеркальная тема, нет новых сообщений\' size=\'+1\' color=\'88A0C0\'>&#9632;</font>',1,16),
(1628,'B_MIRRORED_NO','<img src=\'<#IMG_DIR#>/f_mirrored_no.gif\' border=\'0\' alt=\'Зеркальная тема, нет новых сообщений\'>',1,17),
(1629,'CODE_WRAP_ON','<img src=\'<#IMG_DIR#>/word_wrap_on.gif\' border=\'0\' alt=\'Wrap enabled\'>',1,11),
(1630,'CODE_WRAP_OFF','<img src=\'<#IMG_DIR#>/word_wrap_off.gif\' border=\'0\' alt=\'Wrap disabled\'>',1,11),
(1631,'CODE_WRAP_ON','<img src=\'<#IMG_DIR#>/word_wrap_on.gif\' border=\'0\' alt=\'Wrap enabled\'>',1,12),
(1632,'CODE_WRAP_OFF','<img src=\'<#IMG_DIR#>/word_wrap_off.gif\' border=\'0\' alt=\'Wrap disabled\'>',1,12),
(1633,'CODE_WRAP_ON','<img src=\'<#IMG_DIR#>/word_wrap_on.gif\' border=\'0\' alt=\'Wrap enabled\'>',1,13),
(1634,'CODE_WRAP_OFF','<img src=\'<#IMG_DIR#>/word_wrap_off.gif\' border=\'0\' alt=\'Wrap disabled\'>',1,13),
(1635,'CODE_WRAP_ON','Wrap on',1,16),
(1636,'CODE_WRAP_OFF','Wrap off',1,16),
(1637,'CODE_WRAP_ON','<img src=\'<#IMG_DIR#>/word_wrap_on.gif\' border=\'0\' alt=\'Wrap enabled\'>',1,17),
(1638,'CODE_WRAP_OFF','<img src=\'<#IMG_DIR#>/word_wrap_off.gif\' border=\'0\' alt=\'Wrap disabled\'>',1,17),
(1639,'CODE_COLLAPSE_ON','<img src=\'<#IMG_DIR#>/max_code.gif\' border=\'0\' alt=\'Collapsed\'>',1,11),
(1640,'CODE_COLLAPSE_OFF','<img src=\'<#IMG_DIR#>/min_code.gif\' border=\'0\' alt=\'Expanded\'>',1,11),
(1641,'CODE_COLLAPSE_ON','<img src=\'<#IMG_DIR#>/max_code.gif\' border=\'0\' alt=\'Collapsed\'>',1,12),
(1642,'CODE_COLLAPSE_OFF','<img src=\'<#IMG_DIR#>/min_code.gif\' border=\'0\' alt=\'Expanded\'>',1,12),
(1643,'CODE_COLLAPSE_ON','<img src=\'<#IMG_DIR#>/max_code.gif\' border=\'0\' alt=\'Collapsed\'>',1,13),
(1644,'CODE_COLLAPSE_OFF','<img src=\'<#IMG_DIR#>/min_code.gif\' border=\'0\' alt=\'Expanded\'>',1,13),
(1645,'CODE_COLLAPSE_ON','Expand',1,16),
(1646,'CODE_COLLAPSE_OFF','Collapse',1,16),
(1647,'CODE_COLLAPSE_ON','<img src=\'<#IMG_DIR#>/max_code.gif\' border=\'0\' alt=\'Collapsed\'>',1,17),
(1648,'CODE_COLLAPSE_OFF','<img src=\'<#IMG_DIR#>/min_code.gif\' border=\'0\' alt=\'Expanded\'>',1,17),
(1649,'CODE_NUMBERING_ON','<img src=\'<#IMG_DIR#>/line_num_on.gif\' border=\'0\' alt=\'Line numbers on\'>',1,11),
(1650,'CODE_NUMBERING_OFF','<img src=\'<#IMG_DIR#>/line_num_off.gif\' border=\'0\' alt=\'Line numbers off\'>',1,11),
(1651,'CODE_NUMBERING_ON','<img src=\'<#IMG_DIR#>/line_num_on.gif\' border=\'0\' alt=\'Line numbers on\'>',1,12),
(1652,'CODE_NUMBERING_OFF','<img src=\'<#IMG_DIR#>/line_num_off.gif\' border=\'0\' alt=\'Line numbers off\'>',1,12),
(1653,'CODE_NUMBERING_ON','<img src=\'<#IMG_DIR#>/line_num_on.gif\' border=\'0\' alt=\'Line numbers on\'>',1,13),
(1654,'CODE_NUMBERING_OFF','<img src=\'<#IMG_DIR#>/line_num_off.gif\' border=\'0\' alt=\'Line numbers off\'>',1,13),
(1655,'CODE_NUMBERING_ON','Line numbers',1,16),
(1656,'CODE_NUMBERING_OFF','<s>Line numbers</s>',1,16),
(1657,'CODE_NUMBERING_ON','<img src=\'<#IMG_DIR#>/line_num_on.gif\' border=\'0\' alt=\'Line numbers on\'>',1,17),
(1658,'CODE_NUMBERING_OFF','<img src=\'<#IMG_DIR#>/line_num_off.gif\' border=\'0\' alt=\'Line numbers off\'>',1,17),
(1659,'P_EDIT_HISTORY','История изменений',1,11),
(1660,'P_EDIT_HISTORY','История изменений',1,12),
(1661,'P_EDIT_HISTORY','История изменений',1,13),
(1662,'P_EDIT_HISTORY','История изменений',1,16),
(1663,'P_EDIT_HISTORY','История изменений',1,17);"
            );//insert into ibf_macro
        } catch (Exception $e) {

        }
    }
}
