<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><% TITLE %></title>
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Pragma" content="no-cache">
    <meta content="no-cache" http-equiv="no-cache">
    <meta name="keywords" content="исходник.ру, исходники.ру">
    <script src="/html/jquery.min.js"></script>
    <% RSS %>
    <% GENERATOR %>
    <% CSS %>
    <% JAVASCRIPT_HEAD %>
</head>
<body <% BODY_DATA_TAGS %> >

<!-- Rating@Mail.ru counter -->
<noindex>
<script>
var _tmr = window._tmr || (window._tmr = []);
_tmr.push({id: "89876", type: "pageView", start: (new Date()).getTime()});
(function (d, w, id) {
  if (d.getElementById(id)) return;
  var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true; ts.id = id;
  ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
  var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
  if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
})(document, window, "topmailru-code");
</script><noscript><div>
<img src="//top-fwz1.mail.ru/counter?id=89876;js=na" style="border:0;position:absolute;left:-9999px;" alt="" />
</div></noscript>
</noindex>
<!-- //Rating@Mail.ru counter -->

<div id="ipbwrapper">
    <% JAVASCRIPT_TOP %>
    <% BOARD HEADER %>
    <% GLOBAL MESSAGE %>
    <% NAVIGATION %>
    <% BOARD %>

    <span style="float: right;">
        <noindex>

        <!-- Yandex SQI -->
        <a href="https://webmaster.yandex.ru/siteinfo/?site=https://forum.sources.ru"
            target="_blank"
            style="text-decoration:none; padding-right:1em;"
            title="Yandex: Site Quality Index">
          <img width="88" height="31" alt="" border="0" src="https://yandex.ru/cycounter?https://forum.sources.ru&theme=light&lang=en"/>
        </a>

        <!-- Rating@Mail.ru logo -->
        <a href="https://top.mail.ru/jump?from=89876">
        <img src="//top-fwz1.mail.ru/counter?id=89876;t=8;l=1" 
        style="border:0;" height="40" width="88" alt="Рейтинг@Mail.ru" /></a>
        <!-- //Rating@Mail.ru logo -->

        </noindex>
    </span>

    <% STATS %>

    <noindex><% COPYRIGHT %></noindex>
    <table width="100%">
        <tr>
            <td><% BOTTOM BANNER %></td>
            <td align="center"><% XAP BANNER %></td>
        </tr>
    </table>

</div>
<!-- <script>if(window.comboInit)setTimeout('comboInit()',10)</script> -->
<% JAVASCRIPT_BOTTOM %>
</body>
</html>
