<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title><% TITLE %></title>
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Pragma" content="no-cache">
    <meta content="no-cache" http-equiv="no-cache">
    <meta name="keywords" content="исходник.ру, исходники.ру">
    <script src="/html/jquery.min.js"></script>
    <% RSS %>
    <% GENERATOR %>
    <% CSS %>
    <% JAVASCRIPT_HEAD %>
</head>
<body <% BODY_DATA_TAGS %> >
<div id="ipbwrapper">
    <% JAVASCRIPT_TOP %>
    <% BOARD HEADER %>
    <% GLOBAL MESSAGE %>
    <% NAVIGATION %>
    <% BOARD %>
    <% STATS %>

    <noindex><% COPYRIGHT %></noindex>
    <table width="100%">
        <tr>
            <td><% BOTTOM BANNER %></td>
            <td align="center"><% XAP BANNER %></td>
        </tr>
    </table>

    <noindex>

        <!--Rating@Mail.ru COUNTER-->
        <script language="JavaScript" type="text/javascript"><!--
            d = document;
            var a = '';
            a += ';r=' + escape(d.referrer)
            js = 10//--></script>
        <script language="JavaScript1.1" type="text/javascript"><!--
            a += ';j=' + navigator.javaEnabled()
            js = 11//--></script>
        <script language="JavaScript1.2" type="text/javascript"><!--
            s = screen;
            a += ';s=' + s.width + '*' + s.height
            a += ';d=' + (s.colorDepth ? s.colorDepth : s.pixelDepth)
            js = 12//--></script>
        <script language="JavaScript1.3" type="text/javascript"><!--
            js = 13//--></script>
        <script language="JavaScript" type="text/javascript"><!--
            d.write('<a href="https://top.mail.ru/jump?from=89876"' +
                ' target="_top"><img src="https://df.c5.b1.a0.top.mail.ru/counter' +
                '?id=89876;t=57;js=' + js + a + ';rand=' + Math.random() +
                '" alt="Rating@Mail.ru"' + ' border="0" height="1" width="1"/></a>');
            if (11 < js)d.write('<' + '!-- ')//--></script>
        <noscript><a
                target="_top" href="https://top.mail.ru/jump?from=89876"><img
                    src="https://df.c5.b1.a0.top.mail.ru/counter?js=na;id=89876;t=57"
                    border="0" height="1" width="1"
                    alt="Rating@Mail.ru"/></a></noscript>
        <script language="JavaScript" type="text/javascript"><!--
            if (11 < js)d.write('--' + '>')//--></script>
        <!--/Rating@Mail.ru COUNTER-->


    </noindex>

</div>
<!-- <script type='text/javascript'>if(window.comboInit)setTimeout('comboInit()',10)</script> -->
<% JAVASCRIPT_BOTTOM %>
</body>
</html>
